// <auto-generated />
using System;
using DataAccess.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.EFCore.Migrations
{
    [DbContext(typeof(TtnContext))]
    [Migration("20211029062549_Update_Schema")]
    partial class Update_Schema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Sttn", b =>
                {
                    b.Property<Guid>("F_GUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<decimal?>("CENA")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<decimal?>("CENT")
                        .HasPrecision(17, 4)
                        .HasColumnType("numeric(17,4)");

                    b.Property<DateTime?>("DTV")
                        .HasColumnType("datetime");

                    b.Property<string>("ED")
                        .HasMaxLength(5)
                        .HasColumnType("char(5)");

                    b.Property<decimal?>("EMK")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<byte>("F_DEL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<long>("F_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("F_TM")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("KMC")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(10)")
                        .IsFixedLength(true);

                    b.Property<decimal?>("KOLE")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal?>("KOLM")
                        .HasPrecision(7, 3)
                        .HasColumnType("numeric(7,3)");

                    b.Property<string>("KPL")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)");

                    b.Property<string>("KT")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<decimal?>("KVC")
                        .HasPrecision(3)
                        .HasColumnType("numeric(3,0)");

                    b.Property<string>("NMC")
                        .HasMaxLength(35)
                        .HasColumnType("char(35)");

                    b.Property<string>("NMT")
                        .HasMaxLength(7)
                        .HasColumnType("char(7)");

                    b.Property<decimal?>("NUK")
                        .HasPrecision(9)
                        .HasColumnType("numeric(9,0)");

                    b.Property<decimal?>("PAM")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("PAV")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(2)
                        .HasColumnType("numeric(2,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("PNC")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("PRC")
                        .HasMaxLength(35)
                        .HasColumnType("char(35)");

                    b.Property<string>("SERT")
                        .HasMaxLength(35)
                        .HasColumnType("char(35)");

                    b.Property<decimal?>("SNDS")
                        .HasPrecision(2)
                        .HasColumnType("numeric(2,0)");

                    b.Property<decimal?>("SRR")
                        .HasPrecision(5)
                        .HasColumnType("numeric(5,0)");

                    b.Property<decimal?>("SUMAM")
                        .HasPrecision(17, 4)
                        .HasColumnType("numeric(17,4)");

                    b.Property<decimal?>("SUMIT")
                        .HasPrecision(17, 4)
                        .HasColumnType("numeric(17,4)");

                    b.Property<decimal?>("SUMNC")
                        .HasPrecision(17, 4)
                        .HasColumnType("numeric(17,4)");

                    b.Property<decimal?>("SUMNDS")
                        .HasPrecision(17, 4)
                        .HasColumnType("numeric(17,4)");

                    b.Property<decimal?>("SUMP")
                        .HasPrecision(17, 4)
                        .HasColumnType("numeric(17,4)");

                    b.Property<decimal>("SYSN")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal?>("VB")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<decimal?>("VCENA")
                        .HasPrecision(17, 4)
                        .HasColumnType("numeric(17,4)");

                    b.Property<decimal?>("VRV")
                        .HasPrecision(2)
                        .HasColumnType("numeric(2,0)");

                    b.Property<decimal?>("VSUMNDS")
                        .HasPrecision(17, 4)
                        .HasColumnType("numeric(17,4)");

                    b.Property<decimal?>("VSUMP")
                        .HasPrecision(17, 4)
                        .HasColumnType("numeric(17,4)");

                    b.HasKey("F_GUID")
                        .HasName("F_GUID_BD_STTN_API")
                        .IsClustered(false);

                    b.HasIndex("F_ID")
                        .IsUnique()
                        .HasDatabaseName("F_ID")
                        .IsClustered();

                    b.HasIndex("SYSN")
                        .HasDatabaseName("SYSN");

                    b.ToTable("STTN_API");
                });

            modelBuilder.Entity("Domain.Zttn", b =>
                {
                    b.Property<Guid>("F_GUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("ATP")
                        .HasMaxLength(100)
                        .HasColumnType("char(100)");

                    b.Property<string>("AVT")
                        .HasMaxLength(32)
                        .HasColumnType("char(32)");

                    b.Property<decimal?>("CPT")
                        .HasPrecision(2)
                        .HasColumnType("numeric(2,0)");

                    b.Property<string>("CR_KPL")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)");

                    b.Property<string>("CR_KPP")
                        .HasMaxLength(8)
                        .HasColumnType("char(8)");

                    b.Property<string>("CR_USER")
                        .HasMaxLength(15)
                        .HasColumnType("char(15)");

                    b.Property<DateTime>("DT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(1899, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified));

                    b.Property<DateTime?>("DTDOV")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DTV")
                        .HasColumnType("datetime");

                    b.Property<string>("EKS")
                        .HasMaxLength(30)
                        .HasColumnType("char(30)");

                    b.Property<string>("FIODOV")
                        .HasMaxLength(20)
                        .HasColumnType("char(20)");

                    b.Property<byte>("F_DEL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<long>("F_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("F_TM")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal?>("KATP")
                        .HasPrecision(5)
                        .HasColumnType("numeric(5,0)");

                    b.Property<string>("KAVT")
                        .HasMaxLength(12)
                        .HasColumnType("char(12)");

                    b.Property<decimal?>("KDETD")
                        .HasPrecision(3)
                        .HasColumnType("numeric(3,0)");

                    b.Property<decimal>("KEKS")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5)
                        .HasColumnType("numeric(5,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("KOLM")
                        .HasPrecision(7)
                        .HasColumnType("numeric(7,0)");

                    b.Property<string>("KPL")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasDefaultValue("");

                    b.Property<string>("KPP")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(8)
                        .HasColumnType("char(8)")
                        .HasDefaultValue("");

                    b.Property<string>("KSK")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<string>("KSMEN")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasDefaultValue("");

                    b.Property<decimal?>("KURS")
                        .HasPrecision(16, 8)
                        .HasColumnType("numeric(16,8)");

                    b.Property<string>("KV")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)");

                    b.Property<decimal>("ND")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(9)
                        .HasColumnType("numeric(9,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("NDOV")
                        .HasPrecision(10)
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal?>("NDS10")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("NDS20")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<string>("NPR")
                        .HasMaxLength(7)
                        .HasColumnType("char(7)");

                    b.Property<decimal>("NR")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("numeric(3,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("NSV")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("NUMPL")
                        .HasPrecision(9)
                        .HasColumnType("numeric(9,0)");

                    b.Property<string>("OKPO")
                        .HasMaxLength(12)
                        .HasColumnType("char(12)");

                    b.Property<decimal?>("PCS")
                        .HasPrecision(2)
                        .HasColumnType("numeric(2,0)");

                    b.Property<decimal?>("PD")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("PS")
                        .HasPrecision(2)
                        .HasColumnType("numeric(2,0)");

                    b.Property<decimal?>("SNSCP")
                        .HasPrecision(9)
                        .HasColumnType("numeric(9,0)");

                    b.Property<decimal?>("SROP")
                        .HasPrecision(3)
                        .HasColumnType("numeric(3,0)");

                    b.Property<decimal?>("SUM10")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("SUM20")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("SUMAM")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("SUMD")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("SUMNC")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("SUMNDS")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("SUMOP")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("SUMP")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("SUMST")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("SUMT")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal>("SYSN")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal?>("TABN")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<decimal?>("TD")
                        .HasPrecision(2)
                        .HasColumnType("numeric(2,0)");

                    b.Property<decimal?>("TIME")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("UNN")
                        .HasMaxLength(12)
                        .HasColumnType("char(12)");

                    b.Property<decimal?>("VB")
                        .HasPrecision(10, 3)
                        .HasColumnType("numeric(10,3)");

                    b.Property<string>("VOD")
                        .HasMaxLength(30)
                        .HasColumnType("char(30)");

                    b.Property<decimal?>("VR")
                        .HasPrecision(3)
                        .HasColumnType("numeric(3,0)");

                    b.Property<decimal?>("VSUMD")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("VSUMOP")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("VSUMP")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("VSUMT")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("V_NDS10")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("V_NDS20")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("V_SUM10")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("V_SUM20")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.Property<decimal?>("V_SUMNDS")
                        .HasPrecision(16, 4)
                        .HasColumnType("numeric(16,4)");

                    b.HasKey("F_GUID")
                        .HasName("F_GUID_BD_ZTTN_API")
                        .IsClustered(false);

                    b.HasIndex("DT")
                        .HasDatabaseName("DTKPL")
                        .HasAnnotation("SqlServer:Include", new[] { "KPL" });

                    b.HasIndex("F_ID")
                        .IsUnique()
                        .HasDatabaseName("F_ID")
                        .IsClustered();

                    b.HasIndex("KPL")
                        .HasDatabaseName("PL_D")
                        .HasAnnotation("SqlServer:Include", new[] { "F_ID" });

                    b.HasIndex("ND")
                        .HasDatabaseName("ND");

                    b.HasIndex("NSV")
                        .HasDatabaseName("NSV");

                    b.HasIndex("SYSN")
                        .HasDatabaseName("SYSN");

                    b.ToTable("ZTTN_API");
                });

            modelBuilder.Entity("Domain.Sttn", b =>
                {
                    b.HasOne("Domain.Zttn", "Zttn")
                        .WithMany("Sttns")
                        .HasForeignKey("SYSN")
                        .HasPrincipalKey("SYSN")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Zttn");
                });

            modelBuilder.Entity("Domain.Zttn", b =>
                {
                    b.Navigation("Sttns");
                });
#pragma warning restore 612, 618
        }
    }
}
